name: Compiling Huggingface Wrapper
on: [push]
jobs:
  Combine-File:
    runs-on: ubuntu-latest
    steps:
      - name: Combine and push files to hub
        uses: actions/checkout@v4
        run: python huggingface/combine_files.py -o huggingface/huggingface_wrapper.py
        run: python huggingface/combine_files.py ./push_to_hub -f huggingface/huggingface_wrapper.py
        