name: Compiling Huggingface Wrapper
on: [push, workflow_dispatch]
jobs:
  Combine-File:
    runs-on: ubuntu-latest
    env: 
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install torch cpu only
        run: pip install torch -c huggingface/requirements.txt --index-url https://download.pytorch.org/whl/cpu
      - name: Install dependencies
        run: pip install -r huggingface/requirements.txt
      - name: Combining Files
        run: python huggingface/combine_files.py -o huggingface/huggingface_wrapper.py
      - name: Formatting generated code
        run: | 
          python -m black huggingface/huggingface_wrapper.py
          python -m isort huggingface/huggingface_wrapper.py 
      - name: Push to hub
        run: python huggingface/push_to_hub.py
        
